#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the insertionSort2 function below.
def insertionSort2(n, arr):
    for i in range(1, n):
        key = arr[i] #second item since the first item is already sorted
        j = i - 1 #last item
        while (j >= 0) and key < arr[j]:
            arr[j + 1]= arr[j] 
            j -= 1 
        arr[j + 1] = key
        print(*arr)
            
if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)

OUTPUT:
1 4 3 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 2 3 4 5 6
